[supervisord]
user=root
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
pidfile=/tmp/supervisord.pid

[program:realtime-server]
command=java -jar claire-server.jar
directory=/app/server
autostart=true
autorestart=true
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:stt-server]
command=/opt/venv/bin/python3 -m uvicorn server:app --host 0.0.0.0 --port 1236
directory=/app/stt-server
autostart=true
autorestart=true
startsecs=70
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:tts-server]
command=/opt/tts-venv/bin/python3 -m uvicorn server:app --host 0.0.0.0 --port 1238
directory=/app/tts-server
autostart=true
autorestart=true
startsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
